- name: Create normal user
  user:
    name: "{{ user_entry.name }}"
    password: "{{ common_password | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
    update_password: always

- name: Force password change on next login
  command: chage -d 0 {{ user_entry.name }}

- name: Add user to sudo group if required
  user:
    name: "{{ user_entry.name }}"
    groups: sudo
    append: yes
  when: user_entry.sudo == 'yes'

