- name: Check if firewalld is installed
  stat:
    path: /usr/lib/systemd/system/firewalld.service
  register: firewalld_status

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: firewalld_status.stat.exists

- name: Check if ufw is installed
  stat:
    path: /usr/sbin/ufw
  register: ufw_status

- name: Disable ufw
  command: ufw disable
  when: ufw_status.stat.exists