- name: Base Setup Playbook
  hosts: all
  become: yes

  tasks:
    - include_tasks: tasks/set_timezone.yml
    - include_tasks: tasks/disable_firewall.yml
    - include_tasks: tasks/install_packages.yml
