- name: Create normal users with password expiry
  hosts: all
  become: yes

  vars:
    user_list: []

  tasks:
    - name: Show collected user list
      debug:
        var: user_list

    - name: Create normal users
      include_tasks: tasks/create_user_normal.yml
      loop: "{{ user_list }}"
      loop_control:
        loop_var: user_entry

